services:
    Beast\VisitorTrackerBundle\:
        resource: '../vendor/beast/visitor-tracker-bundle/'
        exclude: '../vendor/beast/visitor-tracker-bundle/{Entity,Migrations,Tests}'
        autowire: true
        autoconfigure: true


    Beast\VisitorTrackerBundle\Service\VisitorLogConfig:
        arguments:
            $logDir: '%kernel.project_dir%/var/visitor_tracker/logs'
