services:
    App\VisitorTrackerBundle\:
        resource: '../src/VisitorTrackerBundle/*'
        exclude: '../src/VisitorTrackerBundle/{Entity,Migrations,Tests}'
        tags: ['controller.service_arguments']

